# -*- coding: utf-8 -*-
"""
Created on Tue Jan 28 15:51:28 2025

@author: willi
"""

# FILE TO GENERATE ALL FIGURES FOR RSNAPSIM PAPER


import numpy as np
import matplotlib.pyplot as plt
import os

cwd = os.getcwd()
os.chdir('../../')
import rsnapsim as rsnp
os.chdir(cwd)


import numpy as np
import time

import matplotlib.gridspec as gridspec
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
from matplotlib import cm
import matplotlib.patches as mpatches
from matplotlib.collections import PatchCollection
from matplotlib.patches import PathPatch
import multiprocessing
from joblib import Parallel, delayed
import inspect
from itertools import product

import tqdm

##############################################################################
# Plotting style
import matplotlib.pyplot as plt
from cycler import cycler
import matplotlib.cm as cm
from matplotlib.lines import Line2D

colors = [ '#06d6a0','#ef476f', '#7400b8','#073b4c', '#118ab2',]
#colors = ['#fa8174', '#b3de69', '#bc82bd','#ccebc4','#ffed6f','#81b1d2']
font = {'family' : 'sans-serif',
        'weight' : 'bold',
        'size'   : 12}
plt.rcParams.update({'font.size': 12, 'font.weight':'bold', 'font.family':'sans-serif'  }   )
plt.rcParams.update({'axes.prop_cycle':cycler(color=colors)})
plt.rcParams.update({'axes.prop_cycle':cycler(color=colors)})
plt.rcParams.update({'axes.prop_cycle':cycler(color=colors)})
plt.rcParams.update({'xtick.major.width'   : 2.8 })
plt.rcParams.update({'xtick.labelsize'   : 12 })
plt.rcParams.update({'ytick.major.width'   : 2.8 })
plt.rcParams.update({'ytick.labelsize'   : 12})
plt.rcParams.update({'axes.titleweight'   : 'bold'})
plt.rcParams.update({'axes.titlesize'   : 10})
plt.rcParams.update({'axes.labelweight'   : 'bold'})
plt.rcParams.update({'axes.labelsize'   : 12})
plt.rcParams.update({'axes.linewidth':2.8})
plt.rcParams.update({'axes.labelpad':8})
plt.rcParams.update({'axes.titlepad':10})
##############################################################################

#### SET THE RANDOM SEED
np.random.seed(42)
seed = 42

##############################################################################
#### script options and flags

global_dpi = 300

regenerate = True   # remake/rerun the simulations
resave = True       # resave the simulations and overwrite
data_save_folder = './figuredata/' # where to save the simulations

#figure 3 figsize
model_figsize = (7,5)

figure_folder = '.' #where to save the figures
figure_format = '.svg' #what format for the figures

n_model_runs = 500 #for figure 3 how many times to run the models
use_cplus = False # use c++ models vs python for generation of the data (will change the outcomes due to RNG algorithm differences)

##############################################################################


# general functions

def plot_kymograph(soln, title='', filename='', show_states=False, profile_t=-1, plot_range = -1, n=0):
    '''
    
    This function makes the kymographs for figure 3 from a given solution object
    
    Parameters
    ----------
    soln : rsnapsim solution object
        The TASEP solution to plot nicely.
    title : str, optional
        suptitle of the plot. The default is ''.
    filename : str, optional
        filename to save the plot as. The default is ''.
    show_states : bool, optional
        also plot the state array? The default is False.
    profile_t : int, optional
        which time point to generate the ribosomal profile from. The default is -1.
    plot_range : int, optional
        what time point to plot too. The default is -1.
    n : str, optional
        which trajectory to generate the kymograph from. The default is 0.

    Returns
    -------
    '''
    
    fig = plt.figure(tight_layout=True, dpi=global_dpi, figsize = model_figsize)
    if show_states:
        gs = gridspec.GridSpec(3, 2, width_ratios=(4,1,1), height_ratios=(4, 1),)
    else:
        gs = gridspec.GridSpec(2, 2, width_ratios=(4,1), height_ratios=(4, 1),)
    kym = fig.add_subplot(gs[0,0])
    intense = fig.add_subplot(gs[0, 1])
    profile = fig.add_subplot(gs[1,0])
    if show_states:
        states = fig.add_subplot(gs[0,2])
    
    un = len(np.unique(soln.ribosome_array[n][:,:,0]))
    for i in np.unique(soln.ribosome_array[n][:,:,0]):
        if i != 0:
            rib_traj = soln.ribosome_array[n][soln.ribosome_array[n][:,:,0]==i]
            kym.plot( rib_traj[:,3], soln.t[np.where(soln.ribosome_array[n][:,:,0]==i)[0]], color=cm.viridis(i/un))
    
    kym.set_ylabel('Time (s)')
    kym.set_ylim([0, soln.t[plot_range]])
    kym.invert_yaxis()
    kym.set_title('Ribosome movement', fontsize=12, loc='left')
    kym.set_xticks([])
    
    
    intense.plot(soln.I[n], soln.t)
    intense.set_ylim([0, soln.t[plot_range]])
    intense.invert_yaxis()
    intense.set_yticks([])
    intense.set_title('Intensity', fontsize=8)
    ticks = np.round(np.linspace(0,np.max(soln.I)+10, 5).astype(int),decimals=-1 )
    intense.get_xaxis().set_ticks(ticks)
    intense.get_xaxis().set_ticklabels([str(x) for x in ticks], rotation=270, fontsize=6)
    ncolors=soln.n_colors
    intense.legend(['C' + str(x+1) for x in range(ncolors)], fontsize=6, bbox_to_anchor=(1,.96), loc='best')
    

    def movmean(a, w=3):
        ret = np.cumsum(a, dtype=float)
        ret[w:] = ret[w:] - ret[:-w]
        return ret[w - 1:] / w


    profile.plot(movmean(np.mean(soln.lattice_arr[:,profile_t,:],axis=0),20),)
    profile.set_ylabel('Density')
    profile.set_xlabel('Codon')
    profile.invert_yaxis()
    profile.set_title('n=%s mRNAs'%str(int(soln.n_traj)), fontsize=6, loc='left')
    
    if show_states:
        s_arr = np.zeros([len(soln.t),1]);
        for i in range(soln.t):
          if soln.state_array[0][i,0] == 0 and soln.state_array[0][i,1] == 0:
            s_arr[i,0] = 0
          if soln.state_array[0][i,0] == 1 and soln.state_array[0][i,1] == 0:
            s_arr[i,0] = 1
          if soln.state_array[0][i,0] == 0 and soln.state_array[0][i,1] == 1:
            s_arr[i,0] = 2
          if soln.state_array[0][i,0] == 1 and soln.state_array[0][i,1] == 1:
            s_arr[i,0] = 3
        
        states.plot(s_arr, soln.t, lw=.5)
        states.scatter(s_arr, soln.t, c=[[colors[0], colors[2], colors[4], colors[1]][int(i)] for i in s_arr], edgecolor='none', s=3, zorder=2)
        states.invert_yaxis()
        states.set_yticks([])
        states.set_title('States', fontsize=8)
        states.set_xlim([-1,4])
        states.get_yaxis().set_visible(False)
        states.get_xaxis().set_ticks([0,1,2,3])
        states.get_xaxis().set_ticklabels(['CAP Off/IRES Off', 'CAP On/IRES Off', 'CAP Off/IRES On','CAP On/IRES On'], rotation=90, fontsize=6)


    fig.suptitle(title)
    if resave:
        plt.savefig('%s/%s%s'%(figure_folder,filename,figure_format))


def plot_spot_types(soln, n=4, title='', filename='', xtick_labels='', int_thresh=5):
    '''
    This function makes the spot type bar charts for figure 3, given a solution object

    Parameters
    ----------
    soln : rsnapsim solution object
        soln to generate spot types from.
    n : int, optional
        how many spot types? For example, 4 spot types for 2 colors: no int, C1, C2, C1+C2. The default is 4.
    title : str, optional
        title of the plot. The default is ''.
    filename : str, optional
        filename to save the plot as. The default is ''.
    xtick_labels : list, optional
        list of strings to replace the xtick labels. The default is ''.
    int_thresh : int, optional
        Intensity threshold to consider that a spot contains a given color. The default is 5.

    Returns
    -------
    None.

    '''
    
    spottypes = [0,]*n
    if n == 4:
        I = soln.I
        for i in range(soln.n_traj):
          c1,c2 = I[i,-1,:]
          if c1 > int_thresh and c2 > int_thresh:
            spottypes[3] = spottypes[3] +1
          if c1 <= int_thresh and c2 > int_thresh:
            spottypes[2] = spottypes[2] +1
          if c1 > int_thresh and c2 <= int_thresh:
            spottypes[1] = spottypes[1] +1
          if c1 <= int_thresh and c2 <= int_thresh:
            spottypes[0] = spottypes[0] +1

    plt.figure(dpi=global_dpi)
    plt.bar([x for x in range(n)],np.array(spottypes)/np.sum(spottypes),color=[colors[2],colors[1], colors[0], colors[3]][:n])
    plt.gca().set_xticks([x for x in range(n)])
    plt.gca().set_xticklabels(xtick_labels)
    plt.text(2.1,.9, 'n = %s mRNAs'%str(soln.n_traj))
    for i in range(n):
        plt.text(i-.3,spottypes[i]/np.sum(spottypes) + .05, r'%s (%.2f)'%(spottypes[i], spottypes[i]/np.sum(spottypes)))

    plt.gca().set_ylim([0,1])
    plt.ylabel('percentage')



    
##############################################################################



# Figure 1
# rSNAPsim package environment

# Figure 2
# mRNA translation dynamics and TASEP description, could be supplemental

# Figure 3
# examples of the model maker and usage


# first model: CAP-IRES - setup the sequences and protein objects
amanda_IRES = '''atgataataGCTAGCTCTGGAGGAGAAGAACTTTTGAGCAAGAATTATCATCTTGAGAACGAAGTGGCTCGTCTTAAGAAAGGTTCTGGCAGTGGAGAAGAACTGCTTTCAAAGAATTACCACCTGGAAAATGAGGTAGCTAGACTGAAAAAGGGGAGCGGAAGTGGGGAGGAGTTGCTGAGCAAAAATTATCATTTGGAGAACGAAGTAGCACGACTAAAGAAAGGGTCCGGATCGGGTGAGGAGTTACTCTCGAAAAATTATCATCTCGAAAACGAAGTGGCTCGGCTAAAAAAGGGCAGTGGTTCTGGAGAAGAGCTATTATCTAAAAACTACCACCTCGAAAATGAGGTGGCACGCTTAAAAAAGGGAAGTGGCAGTGGTGAAGAGCTACTATCCAAGAATTATCATCTTGAGAACGAGGTAGCGCGTTTGAAGAAGGGTTCCGGCTCAGGAGAGGAACTGCTCTCGAAGAACTATCATCTTGAAAATGAGGTCGCTCGATTAAAAAAGGGATCGGGCAGTGGTGAGGAACTACTTTCAAAGAATTACCACCTCGAAAACGAAGTAGCTCGATTAAAGAAAGGTTCAGGGTCGGGTGAAGAATTACTGAGTAAAAATTATCATCTGGAAAATGAGGTAGCGAGACTAAAAAAGGGGAGTGGTTCTGGCGAAGAGTTGCTATCGAAAAATTATCATCTTGAGAACGAAGTTGCTAGGCTCAAAAAGGGCTCAGGCTCAGGCGAGGAGTTGCTCTCGAAAAACTACCACTTGGAAAATGAGGTCGCGAGGTTGAAAAAGGGGAGCGGGTCGGGCGAGGAGTTATTGAGCAAAAACTATCATTTAGAGAACGAAGTCGCGCGCTTAAAGAAAGGCTCGGGCTCGGGCGAAGAACTCTTATCGAAGAACTACCACCTCGAAAATGAGGTCGCCAGGTTGAAAAAGGGCAGTGGCAGCGGGGAGGAACTCTTGAGCAAGAACTACCACTTGGAGAATGAGGTCGCGAGATTGAAGAAAGGGTCGGGGAGCGGCGAGGAATTGCTCAGCAAGAATTATCATTTGGAGAACGAAGTCGCCAGGCTCAAGAAAGGCTCGGGGTCGGGGGAGGAATTGTTGAGTAAAAACTACCACTTGGAAAATGAAGTCGCCAGGCTCAAAAAAGGGAGTGGGAGCGGCGAAGAGTTATTGAGCAAAAATTACCACTTGGAGAACGAAGTGGCAAGGCTCAAGAAAGGGAGCGGCAGCGGGGAGGAGCTCTTATCGAAGAACTACCACTTAGAGAATGAAGTCGCCCGCTTGAAGAAAGGCTCGGGGAGCGGGGAAGAGCTCTTGAGCAAGAACTACCACTTGGAAAATGAGGTGGCGCGCTTGAAGAAAGGGAGCGGGAGCGGGGAAGAGTTACTATCTAAGAATTATCATCTCGAGAACGAGGTGGCTCGACTAAAGAAGGGCTCCGGCAGTGGGGAGGAACTCCTGTCGAAGAACTATCATCTTGAAAATGAGGTTGCAAGACTTAAAAAGGGGTCCGGATCAGGTGAGGAACTACTCAGTAAGAATTACCACCTGGAAAACGAAGTTGCACGTTTGAAGAAAGGATCAGGATCAGGCGAAGAACTGCTCTCAAAAGATTATCATTTGGAAAATGAGGTTGCACGTTTAAAAAAGGGAAGTGGCAGTGGTGAGGAACTTCTGTCGAAAAATTATCATCTCGAGAATGAAGTAGCCCGACTTAAAAAGGGTTCTGGCTCGGGTCAGCGGCCGCACCGGTCAGCAGTGGAGGACAGCACGCTGCAAGTAGTGGTACGGGTGCGGCCCCCCACCCCTCGGGAGCTGGACAGTCAGCGGCGGCCAGTGGTTCAGGTGGTGGACGAGCGGGTGCTGGTGTTTAACCCTGAGGAGCCCGATGGAGGGTTCCCTGGCCTGAAATGGGGTGGCACCCATGATGGCCCCAAGAAGAAGGGCAAAGACCTGACGTTTGTCTTTGACCGGGTCTTTGGCGAGGCGGCCACCCAACAGGACGTGTTCCAGCACACCACGCACAGCGTCCTGGACAGCTTCCTCCAGGGCTACAACTGCTCAGTGTTTGCCTACGGGGCCACCGGGGCTGGGAAGACACACACCATGCTGGGAAGGGAGGGGGACCCCGGCATCATGTACCTGACCACCGTGGAACTGTACAGGCGCCTGGAGGCCCGCCAGCAGGAGAAGCACTTCGAGGTGCTCATCAGCTACCAGGAGGTGTATAATGAACAGATCCATGACCTCCTGGAGCCCAAGGGGCCCCTTGCCATCCGCGAGGACCCCGACAAGGGGGTGGTGGTGCAAGGACTTTCTTTCCACCAGCCAGCCTCAGCCGAGCAGCTGCTGGAGATACTGACCAGGGGGAACCGTAACCGCACGCAGCACCCCACTGATGCCAACGCGACTTCCTCCCGCTCCCATGCCATCTTCCAGATCTTTGTGAAGCAGCAGGACCGGGTTCCAGGACTGACCCAGGCTGTCCAGGTGGCCAAGATGAGCCTGATTGACCTGGCTGGCTCAGAGCGGGCATCCAGCACCCATGCGAAGGGGGAGCGGCTGCGGGAGGGGGCCAACATCAACCGCTCTCTGCTGGCGCTCATCAACGTCCTCAATGCCTTGGCCGATGCAAAGGGCCGCAAGACCGCTGTGCCCTACGCGGACAGCGCACTGACCCGCCTGCTCAAAGACTCCCTCGGGGGCAACTGCCGCACAGTGATGATCGCTGCCATCAGCCCCTCCAGCCTGACCTACGAGGACACGTATAATACCCTCAAATATGCCGACCGGGCCAAGGAGATCAGGCTCTCGCTGAAGAGCAATGTGACCAGCCTGGACTGTCACATCAGCCAGTATGCTACCATCTGCCAACAGCTCCAGGCTGAGGTAGCCGCTCTGAGGAAGAAGCTCCAAGTGTATGAGGGGGGAGGCCAGCCCCCACCACAGGACCTCCCAGGATCTCCCAAGTCGGGACCACCACCAGAACACCTTCCCAGCTCCCCCTTGCCACCCCACCCTCCCAGCCAGCCCTGCACCCCAGAGCTCCCTGCAGGGCCTAGAGCCCTTCAAGAGGAGAGTCTGGGGATGGAGGCCCAGGTGGAGAGGGCCATGGAAGGGAACTCTTCAGACCAGGAGCAGTCCCCAGAGGATGAGGATGAAGGCCCAGCTGAGGAGGTTCCAACCCAGATGCCAGAGCAGAACCCCACACATGCACTGCCAGAGTCCCCTCGCCTGACCCTGCAGCCCAAGCCAGTCGTGGGCCACTTCTCAGCACGGGAACTGGATGGGGACCGTTCTAAGCGGTTGGCCCTAAAGGTGCTGTGCGTTGCCCAGCGGCAGTACTCCCTGCTCCAAGCAGCCAACCTCCTGACGCCCGACATGATCACAGAGTTTGAGACCCTACAGCAGCTGGTGCAAGAGGAAAAAATTGAGCCTGGGGCAGAGGCCTTGAGGACTTCAGGCCTGGCCAGGGGGGCACCTCTGGCTCAGGAGCTGTGTTCAGAGTCAAAGCCTCCAGGATACACTGGCCCTGTGACCCGGACTATGGCGAGGCGACTGAGTGGCCCCCTGCACACCCTGGGAATCCCGCCTGGACCCAACTGCACCCCAGCCCAGGGGTCCCGATGGCCCATGGAGAAGAAGAGGAGGAGACCAAGCGCCTTGGAGGCAGACAGTCCCATGGCCCCAAAGCGGGGCACCAAGCGCCAGCGCCAGTCCTTCCTGCCCTGCCTAAGGAGAGGGTCTCTGCCTGACACCCAACCTTCACAGGGGCCCAGCACCCCCAAAGGAGAAAGGGCCTCCTCCCCCTGCCATTCCCCTCGCGTTTGCCCAGCCACAGTCATCAAAAGCCGGGTGCCCCTGGGCCCTTCCGCCATGCAGAACTGCTCCACCCCGCTGGCTCTGCCCACTCGAGACCTCAATGCCACCTTTGATCTCTCTGAGGAGCCTCCCTCAAAGCCCAGTTTCCATGAATGCATTGGCTGGGACAAAATACCCCAGGAGCTGAGCAGGCTGGACCAGCCCTTCATCCCCAGGGCACCTGTGCCCCTGTTCACCATGAAGGGCCCCAAGCCAACATCTTCCCTCCCTGGGACCTCTGCCTGCAAGAAGAAGCGCGTTGCGAGTTCCTCAGTCTCCCATGGCCGCAGCCGCATCGCCCGCCTCCCCAGCAGCACTTTGAAGAGGCCAGCTGGGCCCCTTGTACTCCCAGAGCTGCCCTTGAGTCCCCTGTGCCCTAGCAACCGGAGGAATGGAAAGGACCTCATCAGGGTGGGGAGAGCACTCTCAGCAGGGAACGGCGTCACCAAGGTGTCCGATAAGGACCTAGGCGGACTGTTACTGAGCTGCGTTTTACACCCTTTCTTTGACAAAACCTAA'''
amanda_CAP = '''ATGGACTACAAGGACGACGACGACAAAGGTGACTACAAAGATGATGACGATAAAGGCGACTATAAGGACGATGACGACAAGGGCGGAAACTCACTGATCAAGGAAAACATGCGGATGAAGGTGGTGATGGAGGGCTCCGTGAATGGTCACCAGTTCAAGTGCACCGGAGAGGGAGAGGGAAACCCGTACATGGGAACTCAGACCATGCGCATTAAGGTCATCGAAGGAGGTCCGCTGCCGTTCGCTTTCGATATCCTGGCCACTTCGTTCGGAGGAGGGTCGCGCACGTTCATCAAGTACCCGAAGGGAATCCCGGACTTCTTTAAGCAGTCATTCCCGGAAGGATTCACTTGGGAACGGGTGACCCGGTATGAAGATGGAGGTGTGGTGACTGTCATGCAAGATACTTCGCTGGAGGATGGGTGCCTCGTGTACCACGTCCAAGTCCGCGGAGTGAATTTCCCGTCCAACGGACCAGTGATGCAGAAAAAGACGAAGGGTTGGGAACCTAATACTGAAATGATGTACCCCGCAGACGGAGGGCTGAGGGGCTACACCCACATGGCGCTGAAGGTCGACGGAGGAGATTACAAGGATGACGACGATAAGCAACAAGATTACAAAGACGATGATGACAAGGGCCAGCAGGGCGACTACAAGGACGACGACGACAAGCAGCAGGACTACAAAGATGACGATGATAAAGGAGGAGGACATCTGTCCTGTTCGTTCGTGACCACCTACAGATCAAAGAAAACCGTGGGAAACATCAAGATGCCGGGCATTCATGCCGTCGACCACCGCCTGGAGCGGCTCGAAGAATCAGACAATGAGATGTTCGTCGTGCAAAGAGAACATGCCGTGGCCAAGTTCGCGGGACTGGGAGGCGGTGGAGGCGATTACAAAGACGATGATGACAAGGGTGACTATAAAGACGACGATGACAAAGGGGATTACAAGGATGATGATGATAAGGGAGGCGGTGGATCAGGTGGAGGAGGTTCACTGCAGGCGATCGCCATGGAGGCGGCCACCACACTGCACCCAGGCCCGCGCCCGGCGCTGCCCCTCGGGGGCCCGGGCCCGCTGGGCGAGTTCCTGCCTCCACCCGAGTGCCCGGTCTTCGAACCCAGCTGGGAAGAGTTCGCGGACCCCTTCGCTTTCATCCACAAGATCCGGCCCATAGCCGAGCAGACTGGCATCTGTAAGGTGCGGCCGCCGCCGGATTGGCAGCCACCATTTGCATGTGATGTTGATAAACTTCATTTTACGCCACGTATCCAGAGACTGAATGAATTGGAGGCCCAAACTCGTGTAAAATTGAATTTCTTGGACCAGATTGCAAAGTACTGGGAGTTACAGGGAAGTACTCTGAAAATTCCACATGTGGAGAGGAAGATCTTGGACTTATTTCAGCTTAATAAGTTAGTTGCAGAAGAAGGTGGATTTGCAGTTGTTTGCAAGGATAGAAAATGGACCAAAATTGCTACCAAGATGGGGTTTGCTCCTGGCAAAGCAGTGGGCTCACATATCAGAGGGCATTATGAACGAATTCTCAACCCCTACAACTTATTCCTGTCCGGAGACAGCCTAAGGTGTTTGCAGAAGCCAAACCTGACCACAGACACTAAGGACAAGGAGTACAAACCCCATGATATTCCCCAGAGGCAGTCTGTGCAGCCTTCGGAAACGTGCCCCCCAGCCCGACGAGCAAAACGCATGAGAGCAGAGGCCATGAATATTAAAATAGAACCCGAGGAGACAACAGAAGCCAGAACTCATAATCTGAGACGTCGAATGGGTTGTCCAACTCCAAAATGTGAAAATGAGAAAGAAATGAAGAGTAGCATCAAGCAAGAACCTATTGAGAGGAAAGATTATATTGTAGAAAATGAGAAGGAAAAGCCCAAGAGTCGATCTAAAAAAGCCACCAATGCTGTGGACCTGTATGTCTGTCTTTTATGTGGCAGTGGCAATGATGAAGACCGGCTACTGTTGTGTGATGGCTGTGATGACAGTTACCATACCTTTTGCTTGATCCCACCTCTCCATGATGTTCCCAAGGGAGACTGGAGGTGTCCTAAGTGTTTGGCTCAGGAATGTAGTAAGCCACAAGAAGCATTTGGCTTTGAACAAGCAGCCAGGGACTATACCCTCCGTACTTTTGGGGAAATGGCAGATGCGTTCAAATCTGATTACTTCAACATGCCAGTCCATATGGTCCCCACAGAGCTTGTTGAGAAAGAATTTTGGAGACTAGTAAGCACTATTGAGGAGGATGTCACAGTGGAATATGGAGCTGACATTGCCTCAAAGGAATTTGGCAGTGGCTTTCCTGTCCGAGATGGGAAAATCAAACTCTCACCTGAGGAAGAGGAGTATCTTGATAGTGGCTGGAATTTGAACAACATGCCAGTGATGGAGCAGTCTGTCCTTGCACATATTACTGCTGATATATGTGGCATGAAACTTCCTTGGTTGTATGTGGGAATGTGCTTTTCTTCATTCTGTTGGCACATTGAAGACCACTGGAGCTATTCAATTAACTACTTGCACTGGGGTGAGCCAAAAACCTGGTATGGAGTCCCAGGGTATGCTGCTGAGCAGCTAGAAAATGTAATGAAGAAACTAGCTCCAGAACTCTTTGTGTCCCAGCCGGATCTCCTCCATCAGCTTGTGACCATCATGAACCCCAATACCCTGATGACTCATGAAGTGCCTGTTTACCGAACTAATCAGTGTGCTGGGGAGTTTGTGATTACATTTCCAAGAGCCTACCACAGTGGTTTTAACCAGGGTTTTAATTTTGCTGAGGCTGTTAACTTCTGCACTGTTGATTGGCTGCCATTAGGCCGACAGTGTGTGGAGCATTATCGCTTGCTTCATCGATATTGTGTGTTTTCCCACGATGAGATGATCTGCAAGATGGCTTCCAAGGCTGATGTATTAGATGTTGTAGTGGCTTCAACTGTTCAGAAAGACATGGCCATTATGATTGAGGATGAGAAAGCTTTAAGAGAAACTGTCCGTAAATTGGGAGTGATTGATTCGGAAAGAATGGATTTTGAGCTGTTGCCAGATGATGAACGTCAGTGTGTAAAATGCAAAACTACATGCTTCATGTCTGCCATCTCCTGTTCTTGTAAACCTGGCCTTCTTGTTTGCCTGCATCATGTAAAAGAATTGTGTTCCTGTCCTCCTTATAAATATAAATTGCGGTATAGGTACACGCTGGATGATCTCTACCCTATGATGAATGCATTGAAGCTTCGAGCAGAATCTTACAACGAATGGGCCTTGAATGTGAATGAAGCTTTGGAGGCAAAGATCAACAAGAAGAAAAGCCTTGTCAGCTTCAAGGCTTTAATTGAAGAATCTGAAATGAAGAAATTCCCAGACAATGATCTTTTGCGACACCTTCGCCTAGTCACACAGGATGCAGAGAAGTGTGCCTCTGTTGCGCAGCAGTTGCTTAATGGCAAAAGGCAAACTAGATATCGATCTGGTGGAGGGAAATCCCAAAATCAGTTGACAGTGAATGAGCTCCGGCAGTTTGTAACACAGCTGTATGCTCTTCCATGTGTCCTCAGTCAGACACCATTACTAAAGGATCTCTTGAATCGTGTAGAAGATTTTCAACAGCATAGTCAGAAACTACTCTCTGAGGAAACGCCTAGTGCTGCGGAGCTGCAGGACTTGCTAGATGTCAGCTTTGAATTTGATGTTGAACTTCCACAGCTTGCTGAGATGCGTATCCGTTTGGAACAAGCCCGTTGGCTAGAAGAGGTGCAGCAAGCTTGCCTAGACCCCAGCTCCCTTACTTTAGATGATATGAGACGTCTCATAGACCTAGGGGTAGGGCTGGCCCCGTATTCAGCAGTGGAGAAAGCTATGGCCCGGCTGCAGGAACTGCTCACAGTGTCAGAGCACTGGGACGACAAAGCCAAGAGTCTCCTCAAGGCCAGGCCACGACATTCATTGAATAGCCTTGCTACGGCAGTAAAGGAAATCGAAGAGATCCCTGCATATCTGCCCAATGGTGCGGCTCTGAAAGACTCAGTGCAGAGAGCCAGAGACTGGCTTCAGGATGTAGAGGGCCTGCAGGCTGGAGGACGTGTGCCAGTGTTAGACACACTCATAGAACTTGTTACACGAGGCCGATCTATCCCGGTACATCTGAATTCTTTGCCAAGACTGGAAACCCTAGTAGCTGAGGTTCAGGCTTGGAAAGAATGTGCTGTTAATACATTCTTGACTGAGAATTCTCCATATTCTCTCTTAGAGGTGCTGTGTCCTCGATGTGATATTGGCCTTTTGGGATTGAAAAGGAAGCAGAGAAAGTTAAAGGAGCCCTTGCCAAATGGAAAGAAAAAAAGCACCAAATTAGAGAGTCTGAGTGACCTGGAGAGAGCTTTAACTGAAAGCAAGGAGACTGCTTCAGCTATGGCAACTCTTGGGGAAGCTCGCCTAAGGGAAATGGAAGCCTTGCAGTCTCTCAGACTCGCCAATGAAGGGAAATTGCTGTCGCCTCTCCAAGATGTGGATATAAAAATCTGCCTATGTCAGAAGGCCCCAGCTGCCCCTATGATTCAATGTGAACTCTGCAGGGATGCTTTCCACACCAGTTGTGTGGCGGTACCCAGTATTTCACAGGGCCTGCGAATCTGGCTTTGTCCCCATTGTCGGAGGTCAGAGAAACCTCCATTAGAGAAAATTCTGCCCCTGCTCGCCTCCCTTCAGCGTATCCGAGTTCGCCTTCCTGAGGGAGATGCACTTCGATATATGATTGAAAGAACCGTGAACTGGCAGCACAGAGCCCAGCAACTGCTTTCGTCAGGGAATCTTAAATTTGTGCAAGATCGAGTGGGCTCAGGACTGTTATATAGCAGATGGCAAGCCTCAGCAGGACAGGTGTCAGACACAAACAAGGTATCTCAACCTCCTGGCACAACATCATTTTCTTTGCCTGATGACTGGGACAACAGAACCTCATATTTGCACTCCCCCTTCTCAACTGGACGAAGTTGTATCCCCCTCCATGGTGTTAGTCCAGAAGTGAATGAACTATTGATGGAAGCCCAGCTGCTCCAGGTATCCCTTCCTGAAATTCAGGAACTTTACCAGACTTTACTTGCAAAGCCAAGCCCTGCTCAGCAGACTGACCGAAGCTCACCAGTGAGACCCAGCAGTGAGAAGAATGACTGTTGCCGAGGGAAGCGAGATGGAATTAACAGTCTTGAGAGAAAACTGAAGAGACGCCTGGAAAGAGAGGGCCTCTCCAGTGAGCGGTGGGAACGAGTTAAGAAAATGCGGACCCCCAAAAAGAAGAAAATCAAACTGAGCCACCCCAAGGACATGAACAATTTCAAGTTAGAGAGAGAGCGTAGCTATGAATTAGTTCGTTCTGCTGAAACTCATTCCCTGCCCTCAGACACATCCTATTCCGAACAGGAAGACTCTGAGGATGAAGATGCCATCTGCCCAGCTGTGAGCTGCCTGCAGCCAGAAGGAGATGAGGTGGACTGGGTCCAGTGTGATGGCAGCTGCAATCAGTGGTTTCATCAGGTCTGTGTTGGTGTCTCCCCAGAGATGGCAGAGAAAGAAGACTACATCTGTGTGCGCTGTACTGTGAAGGACGCACCAAGCCGAAAGGTTTAA'''
poi_0 = rsnp.seqmanip.seq_to_CDS_obj(amanda_IRES)
poi_1 = rsnp.seqmanip.seq_to_CDS_obj(amanda_CAP)

cap = poi_1['0'][0]
ires = poi_0['0'][0]

full_construct =amanda_CAP +  amanda_IRES
kelong = rsnp.propf.get_k( full_construct, .03, 1.7, 0)[1:]
kelong[1885] = 0  # Cap stop codon
kelong[-2] = 0 #IRES stop codon
IRES_start = 1886

# model parameters from the paper
k_init_cap = 4.8e-2
k_init_ires = 4.9e-2

k_on_c = 4.8e-4
k_off_c = 2e-3
k_on_i = 1.8e-4
k_off_i = 6.6e-3
k_on_ic = 1.5e-3

kout_cap = 1.7
kout_ires = 1.7


flagtags = cap.tag_epitopes
suntags = ires.tag_epitopes

probe_locations = np.zeros([2,len(kelong)], dtype=np.intc  )
probe_locations[0,flagtags['T_Flag']] = 1
probe_locations[1,np.array([suntags['T_SunTag']]) + IRES_start   ] = 1




probe_locations = np.zeros([2,len(kelong)], dtype=np.intc  )
probe_locations[0,flagtags['T_Flag']] = 1
probe_locations[1,np.array([suntags['T_SunTag']]) + IRES_start   ] = 1



# Make the mRNA object
full_construct = amanda_CAP +  amanda_IRES
poi = rsnp.seqmanip.seq_to_CDS_obj(full_construct) # convert a given sequence to a protein of interest object
mRNA = poi['0'][0]                              # pull out the main open reading frame

# patch to fix protein detection bug with this construct, will fix
mRNA.nt_seq = full_construct
mRNA.aa_seq = rsnp.seqmanip.nt2aa(full_construct)
mRNA.total_length = len(mRNA.aa_seq )
mRNA.tag_types =  ['T_Flag','T_SunTag']
mRNA.tag_epitopes = {'T_Flag': [1,10,19, 195, 205,217, 227,299,308,317],
   'T_SunTag': [1895,1919,1943,1967,1991,2015,2039,2063,2087,2111,2135,2159,2183, 2207, 2231, 2255, 2279, 2303, 2327, 2351,2375,2399,2447]}


mRNA_length = len(kelong)                  # get the length of the mRNA
mRNA.generate_3frame_tags()                     # call to generate all open reading frames tags
mRNA.multiframe_epitopes = [{'T_Flag': [1, 10, 19, 195, 205, 217, 227, 299, 308, 317],
                             'T_SunTag':[1895, 1919, 1943, 1967, 1991, 2015, 2039, 2063, 2087, 2111, 2135, 2159, 2183, 2207, 2231, 2255, 2279, 2303, 2327, 2351, 2375, 2399, 2447]}, {},{}]



model = rsnp.tasep_model(mRNA, 'dropoff') # model object
# Make the kelong mat (manually adding an extra location that is equal to zero, so particles dont run over the simulation)
kelong_mat = np.zeros([3, mRNA_length+1])
kelong_mat[0, :-2] = rsnp.propf.get_k(mRNA.nt_seq, .01, 3, 3)[1:-1]
kelong_mat[1, :-3] = rsnp.propf.get_k(mRNA.nt_seq[1:-2], .1, 3, 3)[1:-1]
kelong_mat[2, :-3] = rsnp.propf.get_k(mRNA.nt_seq[2:-1], .1, 3, 3)[1:-1]
kelong_mat[0, -2] = 0
kelong_mat[0,1885] = 0
kelong_mat[0,3351] = 0
model._kelong_mat = kelong_mat #override the current kelongation mat


probe_mat = np.zeros([3, mRNA_length+1])
probe_mat[0, [1,10,19, 195, 205,217, 227,299,308,317]] = 1
probe_mat[0, [1895,1919,1943,1967,1991,2015,2039,2063,2087,2111,2135,2159,2183, 2207, 2231, 2255, 2279, 2303, 2327, 2351,2375,2399,2447]] = 2
model._probe_mat = probe_mat #override the current kelongation mat

############ resources ####################


############ states ####################

# we need 4 states for cap ires
model.add_states(2, state0=[0,0], names=['cap','IRES'])


# ribosomal initiation CAP
footprint = 9
# first add the reaction, in this case, we want a lattice reaction at the first
# location for a ribosome to bind (excluded)
init = lambda k,t,p,ke,o,l,pr,s,r,nr: ~np.any(l[0:0+footprint])*k*s[0]
model.add_lattice_reaction(init, k_init_cap, rxn_name='initiation_cap', exclusion=1, frame=0, loc=0, dexist=1)

# ribosomal initiation IRES
# first add the reaction, in this case, we want a lattice reaction at the first
# location for a ribosome to bind (excluded)
init_ires = lambda k,t,p,ke,o,l,pr,s,r,nr: ~np.any(l[1886:1886+footprint])*k*s[1]
model.add_lattice_reaction(init_ires, k_init_ires, rxn_name='initiation_ires', exclusion=1, frame=0, loc=1886, dexist=1,)

# Now we need a reaction for ribosomes to leave the lattice frame 0 at the end (location 1885)
leave_cap = lambda k,t,p,ke,o,l,pr,s,r,nr: l[1885]*k #(lattice location 1084 = 1) * parameter
model.add_lattice_reaction(leave_cap, kout_cap, rxn_name='termination_cap', exclusion=0, frame=0, loc=1885, dexist=-1,)

# Now we need a reaction for ribosomes to leave the lattice frame 1 at the end (location 3351)
leave_ires = lambda k,t,p,ke,o,l,pr,s,r,nr: l[3351]*k #(lattice location 1084 = 1) * parameter
model.add_lattice_reaction(leave_ires, kout_ires, rxn_name='termination_ires', exclusion=0, frame=0, loc=3351, dexist=-1,)

############ STATE RXNS ##################

#k_on_c = 4.8e-4
#k_off_c = 2e-3
#k_on_i = 1.8e-4
#k_off_i = 6.6e-3
#k_on_ic = 1.5e-3


# Cap turning on
cap_on = lambda k,t,p,ke,o,l,pr,s,r,nr: (s[0] == 0)*k
model.add_state_reaction(cap_on, k_on_c, rxn_name='mRNA on', inds=[0,1],dstates=[1, 0])

# Cap turning off
cap_off = lambda k,t,p,ke,o,l,pr,s,r,nr: s[0]*k
model.add_state_reaction(cap_off, k_off_c, rxn_name='mRNA off', inds=[0,1],dstates=[-1, 0])

# IRES turning on (cap off)
i_on_c_off = lambda k,t,p,ke,o,l,pr,s,r,nr: (s[1] == 0)*(s[0]==0)*k
model.add_state_reaction(i_on_c_off, k_on_i, rxn_name='i_on_c_off', inds=[0,1], dstates=[0, 1])

# IRES turning off
i_off = lambda k,t,p,ke,o,l,pr,s,r,nr: s[1]*k
model.add_state_reaction(i_off, k_off_i, rxn_name='i_off', inds=[0,1],dstates=[0, -1])

# IRES turning on (cap on)
i_on_c_on = lambda k,t,p,ke,o,l,pr,s,r,nr: (s[1] == 0)*(s[0]==1)*k
model.add_state_reaction(i_on_c_on, k_on_ic, rxn_name='i_on_c_on', inds=[0,1],dstates=[0, 1])


# DEFAULT STEPPING OF ELONGATION USING THE ELONGATION MATRIX
default_step = lambda k,t,p,ke,o,l,pr,s,r,nr:  [(ke[p[i,2], p[i,3]])*(1 - sum(l[p[i,3]+1:p[i,3]+footprint])) for i in range(nr)]
model.add_ribosome_reaction(default_step, 0, rxn_name='elongation', exclusion=1, dloc=1) #default stepping

#initial state
model._state_arr0[0] = 0 #both off
model._state_arr0[1] = 0
# finally specify which reactions are ribosome specific
model._ribosome_reactions = [9]
model._constant_reactions = [0,1,2,3,4,5,6,7,8]

model._lattice_arr0 = np.zeros([model._length+5], dtype=int)


t = np.linspace(0,10000,5001)
if regenerate: 
    #for i in tqdm.tqdm(range(n_model_runs)):
    soln = rsnp.solver.solve_ssa(model, t, n_traj=n_model_runs, burnin=5000, verbose=True)
    if resave:
        soln.save(data_save_folder + 'cap_ires',fmt='.npz')
else:
    soln = rsnp.solver.load_soln(data_save_folder + 'cap_ires.npz')
if resave:
    plt.savefig('%s/cap_ires_model_spots%s'%(figure_folder,figure_format))
    

plot_kymograph(soln, title='CAP-IRES Model', filename='cap_ires_model_kym')
plot_spot_types(soln, n=4, title='CAP-IRES spot types',
                xtick_labels = ['off', 'CAP', 'IRES', 'CAP+IRES'],
                filename='cap_ires_model_kym', int_thresh=5)





############ frameshifting ROA


ken_sequence_frame_0 = '''
AAGAAAAGAATGAACAAGAATTATTGGAATTAGATAAATGGGCAAGTTTGTGGAATTGGTTTAACATAAC
AAATTGGCTGTGGTATATAAAATTATTCATAATGATAGTAGGAGGCTTGGTAGGTTTAAGAATAGTTTTT
GCTGTACTTTCTATAGTGAATAGAGTTAGGCAGGGATATTCACCATTATCGTTTCAGACCCACCTCCCAA
CCCCGAGGGGACCCGACAGGCCCGAAGGAATAGAAGAAGAAGGTGGAGAGAGAGACAGAGACAGATCCAT
TCGATTAGTGAACGGATCTCGACGGTATCGCCGAATTCACAAATGGCAGTATTCATCCACAATTTTAAAA
GAAAAGGGGGGATTGGGGGGTACAGTGCAGGGGAAAGAATAGTAGACATAATAGCAACAGACATACAAAC
TAAAGAATTACAAAAACAAATTACAAAAATTCAAAATTTTCGGGTTTATTACAGGGACAGCAGAGATCCA
GTTTGGACTAGTGGCCTCCGCGCCGGGTTTTGGCGCCTCCCGCGGGCGCCCCCCTCCTCACGGCGAGCGC
TGCCACGTCAGACGAAGGGCGCAGCGAGCGTCCTGATCCTTCCGCCCGGACGCTCAGGACAGCGGCCCGC
TGCTCATAAGACTCGGCCTTAGAACCCCAGTATCAGCAGAAGGACATTTTAGGACGGGACTTGGGTGACT
CTAGGGCACTGGTTTTCTTTCCAGAGAGCGGAACAGGCGAGGAAAAGTAGTCCCTTCTCGGCGATTCTGC
GGAGGGATCTCCGTGGGGCGGTGAACGCCGATGATTATATAAGGACGCGCCGGGTGTGGCACAGCTAGTT
CCGTCGCAGCCGGGATTTGGGTCGCGGTTCTTGTTTGTGGATCGCTGTGATCGTCACTTGGCGGCCGCCA
CCATGTACCCTTATGATGTGCCCGATTATGCTGGCTACCCTTATGATGTTCCTGATTACGCCGGATATCC
GTATGACGTGCCAGACTACGCGGGAGGTGTGAGCAAGGGAGAGGAGTTGTTTACCGGCGTGGTCCCCATA
CTGGTGGAGTTGGATGGCGACGTTAATGGACATAAATTCTCGGTCCGCGGCGAGGGAGAGGGAGACGCCA
CCAATGGCAAGCTGACGCTTAAGTTCATTTGCACGACTGGAAAATTGCCTGTCCCCTGGCCGACCCTGGT
CACCACACTGGGCGGAGGAGTGCAGTGCTTCTCCCGTTACCCAGACCACATGAAGCAGCACGATTTCTTC
AAGAGCGCAATGCCGGAGGGATACGTGCAAGAACGGACTATTTCCTTCAAGGATGACGGAACCTATAAGA
CCCGTGCGGAGGTCAAATTCGAGGGTGACACCCTGGTGAACCGAATTGAACTCAAAGGAATCGATTTCAA
GGAGGATGGAAATATTCTGGGTCACAAGCTGGAATACAACTTCAACAGCCATAATGTGTACATTACGGCT
GATAAGCAGAAGAACGGCATTAAGGCCAATTTCAAGATCCGCCACAACGTTGAGGGTGGATATCCCTACG
ACGTGCCCGATTATGCGGGCGGATATCCGTATGATGTTCCAGATTATGCTGGTGGTGGAGGCTATCCCTA
TGATGTCCCCGACTACGCCGGAGGTTACCCATACGACGTGCCCGACTACGCTGGAGGCGATGGCAGCGTG
CAGCTGGCAGATCATTATCAACAGAATACCCCCATAGGTGATGGCCCCGTTCTGCTTCCAGATAATCACT
ACCTTTCCACCCAGAGCGTGCTTTCGAAAGACCCGAACGAAAAGCGTGATCACATGGTCCTGCTGGAGTT
TGTGACCGCGGCTGGAATCACCCTGGGTATGGACGAACTCTACAAGGGTGGCTACCCCTACGATGTGCCG
GATTACGCTGGATATCCGTATGACGTACCGGACTATGCCGGTTACCCGTACGATGTCCCGGACTACGCTG
GAGGCGGTGGATCAGGTGGAGGAGGTTCACTGCAGGCTCGTGGTACCCTGCATGGTTTTTTAGGGAAGAT
CTGGCCTTCCCACAAGGGAAGGCCAGGGAATTTTCTTCAGAGCAGACCAGAGCCAACAGCCGCACCGTTT
CTAGAGGACTACAAGGACGACGACGACAAAGGGAAGAACTTTTGTCAAAGAATTATCATCTCGAGAACGA
AGTGGCTCGTCTCAAGAAAGGATTACAAAGACGACGACGACAAGGGGAAGAACTGCTTTCAAAGAATTAC
CACCTGGAAAACGAGGTCGCGAGACTCAAAAAGAGATTACAAAGACGACGACGACAAGGGGAAGAATTAC
TCAGCAAAAATTATCATCTGGAAAACGAGGTTGCGAGACTCAAAAAGGGACTACAAAGACGACGACGACA
AAGCGAAGAACTTTTGTCCAAGAATTATCATCTGGAGAACGAAGTGGCTCGTCTCAAGAAAGGATTACAA
GGACGACGACGACAAGGGGAAGAACTGCTTTCAAAGAATTACCACCTGGAAAATGAGGTGGCTAGACTCA
AAAAGGGATTACAAGGACGACGACGACAAGGGGAGGAACTACTTTCAAAGAATTACCACCTCGAAAACGA
AGTGGCTCGACTTAAGAAAGGACTACAAAGACGACGACGACAAGGGGAGGAATTGCTATCGAAAAATTAT
CATCTTGAGAACGAAGTTGCTAGGCTCAAAAAGCGATTACAAGGACGACGACGACAAGCGGAAGAATTAC
TGTCCAAAAATTATCATCTGGAAAATGAGGTGGCGAGACTCAAAAAGGGACTACAAGGACGACGACGACA
AACCGAGGAACTGCTCTCGAAGAACTATCATCTTGAAAATGAGGTCGCTCGACTCAAAAAGAGATTACAA
GGACGACGACGACAAGCAGAAGAGCTATTATCTAAAAACTACCACCTCGAAAATGAGGTGGCACGCCTCA
AAAAGGGATTACAAAGACGACGACGACAAAAGGAAGAGCTACTATCCAAGAATTATCATCTTGAGAACGA
GGTGGCGCGTCTCAAGAAGCGACTACAAGGACGACGACGACAAAGAGAGGAGTTGCTTAGCAAAAATTAT
CATTTGGAGAACGAAGTCGCACGACTCAAGAAAACTAGTGGCGGTCATATGGGCGTGCGCAACTGCCTCT
ACGGCAATAATATGTCAGGACAACGCGATATCCCCCCTGAAATCGGGGAACAGCCCGAGCAACCACCTTT
GGAGGCCCCAGGGGCAGCTGCCCCCGGTGCTGGGCCTAGCCCAGCCGAAGAGATGGAGACCGAACCGCCT
CACAACGAGCCCATCCCCGTCGAGAATGATGGCGAGGCCTGTGGACCCCCAGAGGTCTCCAGACCCAACT
TTCAGGTCCTCAACCCGGCATTCAGGGAAGCTGGAGCCCATGGAAGCTACAGCCCACCTCCTGAGGAAGC
AATGCCCTTCGAGGCTGAACAGCCCAGCTTGGGAGGCTTCTGGCCTACACTGGAGCAGCCTGGATTCCCC
AGTGGGGTCCATGCAGGCCTTGAGGCCTTCGGCCCAGCACTCATGGAGCCCGGAGCCTTCAGTGGTGCCA
GACCAGGCCTGGGAGGATACAGCCCTCCACCAGAAGAAGCTATGCCCTTTGAGTTTGACCAGCCTGCCCA
GAGAGGCTGCAGTCAACTTCTCTTACAGGTCCCAGACCTTGCTCCAGGAGGCCCAGGTGCTGCAGGGGTC
CCCGGAGCTCCTCCCGAGGAGCCCCAAGCCCTCAGGCCTGCAAAGGCTGGCTCCAGAGGAGGCTACAGCC
CTCCCCCTGAGGAGACTATGCCATTTGAGCTTGATGGAGAAGGATTTGGGGACGACAGCCCACCCCCGGG
GCTTTCCCGAGTTATCGCACAAGTCGACGGCAGCAGCCAGTTCGCGGCAGTCGCGGCCTCGAGTGCGGTC
CGCCTCACTCCCGCCGCGAACGCGCCTCCCCTCTGGGTCCCAGGCGCCATCGGCAGCCCATCCCAAGAGG
CTGTCAGACCTCCTTCTAACTTCACGGGCAGCAGCCCCTGGATGGAGATCTCCGGACCCCCGTTCGAGAT
TGGCAGCGCCCCCGCTGGGGTCGACGACACTCCCGTCAACATGGACAGCCCCCCAATCGCGCTTGACGGC
CCGCCCATCAAGGTCTCCGGAGCCCCAGATAAGAGAGAGCGAGCAGAGAGACCCCCAGTTGAGGAGGAAG
CAGCAGAGATGGAAGGAGCCGCTGATGCCGCGGAGGGAGGAAAAGTACCCTCTCCGGGGTACGGATCCCC
TGCCGCCGGGGCAGCCTCAGCGGATACCGCTGCCAGGGCAGCCCCTGCAGCCCCAGCCGATCCTGACTCC
GGGGCAACCCCAGAAGATCCCGACTCCGGGACAGCACCAGCCGATCCTGACTCCGGGGCATTCGCAGCCG
ATCCCGACTCCGGGGCAGCCCCTGCCGCCCCAGCCGATCCCGACTCCGGGGCGGCCCCTGACGCCCCAGC
CGATCCCGACTCCGGGGCGGCCCCTGACGCCCCAGCCGATCCAGATGCCGGGGCGGCCCCTGAGGCTCCC
GCCGCCCCTGCGGCTGCTGAGACCCGGGCAGCCCATGTCGCCCCAGCTGCGCCAGACGCAGGGGCTCCCA
CTGCCCCAGCCGCTTCTGCCACCCGGGCAGCCCAAGTCCGCCGGGCGGCCTCTGCAGCCCCTGCCTCCGG
GGCCAGACGCAAGATCCATCTCAGACCCCCCAGCCCCGAGATCCAGGCTGCCGATCCGCCTACTCCGCGG
CCTACTCGCGCGTCTGCCTGGCGGGGCAAGTCCGAGAGCAGCCGCGGCCGCCGCGTGTACTACGATGAAG
GGGTGGCCAGCAGCGACGATGACTCCAGCGGAGACGAGTCCGACGATGGGACCTCCGGATGCCTCCGCTG
GTTTCAGCATCGGCGAAATCGCCGCCGCCGAAAGCCCCAGCGCAACTTACTCCGCAACTTTCTCGTGCAA
GCCTTCGGGGGCTGCTTCGGTCGATCTGAGAGTCCCCAGCCCAAAGCCTCGCGCTCTCTCAAGGTCAAGA
AGGTACCCCTGGCGGAGAAGCGCAGACAGATGCGCAAAGAAGCCCTGGAGAAGCGGGCCCAGAAGCGCGC
AGAGAAGAAACGCAGTAAGCTCATCGACAAACAACTCCAGGACGAAAAGATGGGCTACATGTGTACGCAC
CGCCTGCTGCTTCTAGGCTAGCTAGGCGGACTGTTACTGAGCTGCGTTTTACACCCTTTCTTTGACAAAA
CCTAACTTGCGCAGAAAAAAAAAAAATAAGAGACAACATTGGCATGGCTTTGTTTAAGCGCTTTTGACTC
AGGATTTAAAAACTGGAACGGTGAAGGCGACAGCAGTTGGTTGGAGCAAACATCCCCCAAAGTTCTACAA
ATGTGGCTGAGGACTTTGTACATTGTTTTGTTTTTTTTTTTTTTGGTTTTGTCTTTTTTTAATAGTCATT
CCAAGTATCCATGAAATAAGTGGTTACAGGAAGTCCCTCACCCTCCCAAAAGCCACCCCCACTCCTAAGA
GGAGGATGGTCGCGTCCATGCCCTGAGTCCACCCCGGGGAAGGTGACAACCGGTAACCTACAAACGGGTG
GAGGATCACCCCACCCGACACTTCACAATCAAGGGGTACAATACACAAGGGTGGAGGAACACCCCACCCT
CCAGACACATTACACAGAAATCCAATCAAACAGAAGCACCATCAGGGCTTCTGCTACCAAATTTATCTCA
AAAAACTACAACAAGGAATCACCATCAGGGATTCCCTGTGCAATATACGTCAAACGAGGGCCACGACGGG
AGGACGATCACGCCTCCCGAATATCGGCATGTCTGGCTTTCGAATTCAGTGCGTGGAGCATCAGCCCACG
CAGCCAATCAGAGTCGAATACAAGTCGACTTTCGCGAAGAGCATCAGCCTTCGCGCCATTCTTACACAAA
CCACACTCTCCCCTACAGGAACAGCATCAGCGTTCCTGCCCAGTACCCAACTCAAGAAAATTTATGTCCC
CATGCAGCATCAGCGCATGGGCCCCAAGAATACATCCCCAACAAAATCACATCCGAGCACCAACAGGGCT
CGGAGTGTTGTTTCTTGTCCAACTGGACAAACCCTCCATGGACCATCAGGCCATGGACTCTCACCAACAA
GACAAAAACTACTCTTCTCGAAGCAGCATCAGCGCTTCGAAACACTCGAGCATACATTGTGCCTATTTCT
TGGGTGGACGATCACGCCACCCATGCTCTCACGAATTTCAAAACACGGACAAGGACGAGCACCACCAGGG
CTCGTCGTTCCACGTCCAATACGATTACTTACCTTTCGGGATCACGATCACGGATCCCGCAGCTACATCA
CTTCCACTCAGGACATTCAAGCATGCACGATCACGGCATGCTCCACAAGTCTCAACCACAGAAACTACCA
AATGGGTTCAGCACCAGCGAACCCACTCCTACCTCAAACCTCTTCCCACAAAACTGGCAAGCAGGATCAC
CGCTTGCCCATTCCAACATACCAAATCAAAAACAATTACTGGTACAGCATCAGCGTACCAGCCCACATCT
CTCACTACTATCAAAAACCAAACCGTTCAGCAACAGCGAACGGTACACACGGAAAAATCAACTGGTTTAC
AAATACGAAAGACGATCACGCTTTCGTCCAGCGCAAACTATTACGAAAAACATCCGACGGGAAGAGCAAC
AGCCTTCCCGCGGCGGAAAACCTCACAAAAACACGACAAACGGATGCACGAACACGGCATCCGCCGACAA
CCCACAAACTTACAACCAGGCAAACGGTGCAGGATCACCGCACCGTACATCAAACACCTCAGATCTCATA
TCGATAGATCCTAATCAACCTCTGGATTACAAAATTTGTGAAAGATTGACTGGTATTCTTAACTATGTTG
CTCCTTTTACGCTATGTGGATACGCTGCTTTAATGCCTTTGTATCATGCTATTGCTTCCCGTATGGCTTT
CATTTTCTCCTCCTTGTATAAATCCTGGTTGCTGTCTCTTTATGAGGAGTTGTGGCCCGTTGTCAGGCAA
CGTGGCGTGGTGTGCACTGTGTTTGCTGACGCAACCCCCACTGGTTGGGGCATTGCCACCACCTGTCAGC
TCCTTTCCGGGACTTTCGCTTTCCCCCTCCCTATTGCCACGGCGGAACTCATCGCCGCCTGCCTTGCCCG
CTGCTGGACAGGGGCTCGGCTGTTGGGCACTGACAATTCCGTGGTGTTGTCGGGGAAATCATCGTCCTTT
CCTTGGCTGCTCGCCTGTGTTGCCACCTGGATTCTGCGCGGGACGTCCTTCTGCTACGTCCCTTCGGCCC
TCAATCCAGCGGACCTTCCTTCCCGCGGCCTGCTGCCGGCTCTGCGGCCTCTTCCGCGTCTTCGCCTTCG
CCCTCAGACGAGTCGGATCTCCCTTTGGGCCGCCTCCCCGCCTGAGATCCTTTAAGACCAATGACTTACA
AGGCAGCTGTAGATCTTAGCCACTTTTTAAAAGAAAAGGGGGGACTGGAAGGGCTAATTCACTCCCAACG
AAGACAAGATCTGCTTTTTGCTTGTACTGGGTCTCTCTGGTTAGACCAGATCTGAGCCTGGGAGCTCTCT
GGCTAACTAGGGAACCCACTGCTTAAGCCTCAATAAAGCTTGCCTTGAGTGCTTCAAGTAGTGTGTGCCC
GTCTGTTGTGTGACTCTGGTAACTAGAGATCCCTCAGACCCTTTTAGTCAGTGTGGAAAATCTCTAGCAG
TAGTAGTTCATGTCATCTTATTATTCAGTATTTATAACTTGCAAAGAAATGAATATCAGAGAGTGAGAGG
CCCGGGTTAATTAAGGAAAGGGCTAGATCATTCTTGAAGACGAAAGGGCCTCGTGATACGCCTATTTTTA
TAGGTTAATGTCATGATAATAATGGTTTCTTAGACGTCAGGTGGCACTTTTCGGGGAAATGTGCGCGGAA
CCCCTATTTGTTTATTTTTCTAAATACATTCAAATATGTATCCGCTCATGAGACAATAACCCTGATAAAT
GCTTCAATAATATTGAAAAAGGAAGAGTATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTT
GCGGCATTTTGCCTTCCTGTTTTTGCTCACCCAGAAACGCTGGTGAAAGTAAAAGATGCTGAAGATCAGT
TGGGTGCACGAGTGGGTTACATCGAACTGGATCTCAACAGCGGTAAGATCCTTGAGAGTTTTCGCCCCGA
AGAACGTTTTCCAATGATGAGCACTTTTAAAGTTCTGCTATGTGGCGCGGTATTATCCCGTGTTGACGCC
GGGCAAGAGCAACTCGGTCGCCGCATACACTATTCTCAGAATGACTTGGTTGAGTACTCACCAGTCACAG
AAAAGCATCTTACGGATGGCATGACAGTAAGAGAATTATGCAGTGCTGCCATAACCATGAGTGATAACAC
TGCGGCCAACTTACTTCTGACAACGATCGGAGGACCGAAGGAGCTAACCGCTTTTTTGCACAACATGGGG
GATCATGTAACTCGCCTTGATCGTTGGGAACCGGAGCTGAATGAAGCCATACCAAACGACGAGCGTGACA
CCACGATGCCTGTAGCAATGGCAACAACGTTGCGCAAACTATTAACTGGCGAACTACTTACTCTAGCTTC
CCGGCAACAATTAATAGACTGGATGGAGGCGGATAAAGTTGCAGGACCACTTCTGCGCTCGGCCCTTCCG
GCTGGCTGGTTTATTGCTGATAAATCTGGAGCCGGTGAGCGTGGGTCTCGCGGTATCATTGCAGCACTGG
GGCCAGATGGTAAGCCCTCCCGTATCGTAGTTATCTACACGACGGGGAGTCAGGCAACTATGGATGAACG
AAATAGACAGATCGCTGAGATAGGTGCCTCACTGATTAAGCATTGGTAACTGTCAGACCAAGTTTACTCA
TATATACTTTAGATTGATTTAAAACTTCATTTTTAATTTAAAAGGATCTAGGTGAAGATCCTTTTTGATA
ATCTCATGACCAAAATCCCTTAACGTGAGTTTTCGTTCCACTGAGCGTCAGACCCCGTAGAAAAGATCAA
AGGATCTTCTTGAGATCCTTTTTTTCTGCGCGTAATCTGCTGCTTGCAAACAAAAAAACCACCGCTACCA
GCGGTGGTTTGTTTGCCGGATCAAGAGCTACCAACTCTTTTTCCGAAGGTAACTGGCTTCAGCAGAGCGC
AGATACCAAATACTGTTCTTCTAGTGTAGCCGTAGTTAGGCCACCACTTCAAGAACTCTGTAGCACCGCC
TACATACCTCGCTCTGCTAATCCTGTTACCAGTGGCTGCTGCCAGTGGCGATAAGTCGTGTCTTACCGGG
TTGGACTCAAGACGATAGTTACCGGATAAGGCGCAGCGGTCGGGCTGAACGGGGGGTTCGTGCACACAGC
CCAGCTTGGAGCGAACGACCTACACCGAACTGAGATACCTACAGCGTGAGCTATGAGAAAGCGCCACGCT
TCCCGAAGGGAGAAAGGCGGACAGGTATCCGGTAAGCGGCAGGGTCGGAACAGGAGAGCGCACGAGGGAG
CTTCCAGGGGGAAACGCCTGGTATCTTTATAGTCCTGTCGGGTTTCGCCACCTCTGACTTGAGCGTCGAT
TTTTGTGATGCTCGTCAGGGGGGCGGAGCCTATGGAAAAACGCCAGCAACGCGGCCTTTTTACGGTTCCT
GGCCTTTTGCTGGCCTTTTGCTCACATGTTCTTTCCTGCGTTATCCCCTGATTCTGTGGATAACCGTATT
ACCGCCTTTGAGTGAGCTGATACCGCTCGCCGCAGCCGAACGACCGAGCGCAGCGAGTCAGTGAGCGAGG
AAGCGGAAGAGCGCCCAATACGCAAACCGCCTCTCCCCGCGCGTTGGCCGATTCATTAATGCAGCAAGCT
CATGGCTGACTAATTTTTTTTATTTATGCAGAGGCCGAGGCCGCCTCGGCCTCTGAGCTATTCCAGAAGT
AGTGAGGAGGCTTTTTTGGAGGCCTAGGCTTTTGCAAAAAGCTCCCCGTGGCACGACAGGTTTCCCGACT
GGAAAGCGGGCAGTGAGCGCAACGCAATTAATGTGAGTTAGCTCACTCATTAGGCACCCCAGGCTTTACA
CTTTATGCTTCCGGCTCGTATGTTGTGTGGAATTGTGAGCGGATAACAATTTCACACAGGAAACAGCTAT
GACATGATTACGAATTTCACAAATAAAGCATTTTTTTCACTGCATTCTAGTTGTGGTTTGTCCAAACTCA
TCAATGTATCTTATCATGTCTGGATCAACTGGATAACTCAAGCTAACCAAAATCATCCCAAACTTCCCAC
CCCATACCCTATTACCACTGCCAATTACCTGTGGTTTCATTTACTCTAAACCTGTGATTCCTCTGAATTA
TTTTCATTTTAAAGAAATTGTATTTGTTAAATATGTACTACAAACTTAGTAGTTGGAAGGGCTAATTCAC
TCCCAAAGAAGACAAGATATCCTTGATCTGTGGATCTACCACACACAAGGCTACTTCCCTGATTAGCAGA
ACTACACACCAGGGCCAGGGGTCAGATATCCACTGACCTTTGGATGGTGCTACAAGCTAGTACCAGTTGA
GCCAGATAAGGTAGAAGAGGCCAATAAAGGAGAGAACACCAGCTTGTTACACCCTGTGAGCCTGCATGGG
ATGGATGACCCGGAGAGAGAAGTGTTAGAGTGGAGGTTTGACAGCCGCCTAGCATTTCATCACGTGGCCC
GAGAGCTGCATCCGGAGTACTTCAAGAACTGCTGATATCGAGCTTGCTACAAGGGACTTTCCGCTGGGGA
CTTTCCAGGGAGGCGTGGCCTGGGCGGGACTGGGGAGTGGCGAGCCCTCAGATCCTGCATATAAGCAGCT
GCTTTTTGCCTGTACTGGGTCTCTCTGGTTAGACCAGATCTGAGCCTGGGAGCTCTCTGGCTAACTAGGG
AACCCACTGCTTAAGCCTCAATAAAGCTTGCCTTGAGTGCTTCAAGTAGTGTGTGCCCGTCTGTTGTGTG
ACTCTGGTAACTAGAGATCCCTCAGACCCTTTTAGTCAGTGTGGAAAATCTCTAGCAGTGGCGCCCGAAC
AGGGACTTGAAAGCGAAAGGGAAACCAGAGGAGCTCTCTCGACGCAGGACTCGGCTTGCTGAAGCGCGCA
CGGCAAGAGGCGAGGGGCGGCGACTGGTGAGTACGCCAAAAATTTTGACTAGCGGAGGCTAGAAGGAGAG
AGATGGGTGCGAGAGCGTCAGTATTAAGCGGGGGAGAATTAGATCGCGATGGGAAAAAATTCGGTTAAGG
CCAGGGGGAAAGAAAAAATATAAATTAAAACATATAGTATGGGCAAGCAGGGAGCTAGAACGATTCGCAG
TTAATCCTGGCCTGTTAGAAACATCAGAAGGCTGTAGACAAATACTGGGACAGCTACAACCATCCCTTCA
GACAGGATCAGAAGAACTTAGATCATTATATAATACAGTAGCAACCCTCTATTGTGTGCATCAAAGGATA
GAGATAAAAGACACCAAGGAAGCTTTAGACAAGATAGAGGAAGAGCAAAACAAAAGTAAGACCACCGCAC
AGCAAGCGGCCGGCCGCTGATCTTCAGACCTGGAGGAGGAGATATGAGGGACAATTGGAGAAGTGAATTA
TATAAATATAAAGTAGTAAAAATTGAACCATTAGGAGTAGCACCCACCAAGGCAAAGAGAAGAGTGGTGC
AGAGAGAAAAAAGAGCAGTGGGAATAGGAGCTTTGTTCCTTGGGTTCTTGGGAGCAGCAGGAAGCACTAT
GGGCGCAGCGTCAATGACGCTGACGGTACAGGCCAGACAATTATTGTCTGGTATAGTGCAGCAGCAGAAC
AATTTGCTGAGGGCTATTGAGGCGCAACAGCATCTGTTGCAACTCACAGTCTGGGGCATCAAGCAGCTCC
AGGCAAGAATCCTGGCTGTGGAAAGATACCTAAAGGATCAACAGCTCCTGGGGATTTGGGGTTGCTCTGG
AAAACTCATTTGCACCACTGCTGTGCCTTGGAATGCTAGTTGGAGTAATAAATCTCTGGAACAGATTTGG
AATCACACGACCTGGATGGAGTGGGACAGAGAAATTAACAATTACACAAGCTTAATACACTCCTTAATTG
AAGAATCGCAAAACCAGC
'''

orf1_nt =''.join(ken_sequence_frame_0.split('\n'))[304*3:1428*3+3*304]
orf2_nt = orf1_nt[:370*3] + orf1_nt[370*3+2:-1]

#ken_sequence_frame_3 = ''.join(ken_sequence_frame_0.split('\n')[304*3:1428*3+3*304])
aa_seq1 = rsnp.seqmanip.nt2aa(orf1_nt)

#ken_sequence_frame_4 = '''ATGAGCACCGCCTCCTCTGGCACAGCCAGTAGTGGGACTGCATCCTCAGGTGCGGGTACCCTGCATGGTTTTTTAGGGAAGATCTGGCCTTCCCACAAGGGAAGGCCAGGGAATTTTCTTCAGAGCAGACCAGAGCCAACAGCCGCACCGTTTCTAGAGGACTACAAGGACGACGACGACAAAGGGAAGAACTTTTGTCAAAGAATTATCATCTCGAGAACGAAGTGGCTCGTCTCAAGAAAGGATTACAAAGACGACGACGACAAGGGGAAGAACTGCTTTCAAAGAATTACCACCTGGAAAACGAGGTCGCGAGACTCAAAAAGAGATTACAAAGACGACGACGACAAGGGGAAGAATTACTCAGCAAAAATTATCATCTGGAAAACGAGGTTGCGAGACTCAAAAAGGGACTACAAAGACGACGACGACAAAGCGAAGAACTTTTGTCCAAGAATTATCATCTGGAGAACGAAGTGGCTCGTCTCAAGAAAGGATTACAAGGACGACGACGACAAGGGGAAGAACTGCTTTCAAAGAATTACCACCTGGAAAATGAGGTGGCTAGACTCAAAAAGGGATTACAAGGACGACGACGACAAGGGGAGGAACTACTTTCAAAGAATTACCACCTCGAAAACGAAGTGGCTCGACTTAAGAAAGGACTACAAAGACGACGACGACAAGGGGAGGAATTGCTATCGAAAAATTATCATCTTGAGAACGAAGTTGCTAGGCTCAAAAAGCGATTACAAGGACGACGACGACAAGCGGAAGAATTACTGTCCAAAAATTATCATCTGGAAAATGAGGTGGCGAGACTCAAAAAGGGACTACAAGGACGACGACGACAAACCGAGGAACTGCTCTCGAAGAACTATCATCTTGAAAATGAGGTCGCTCGACTCAAAAAGAGATTACAAGGACGACGACGACAAGCAGAAGAGCTATTATCTAAAAACTACCACCTCGAAAATGAGGTGGCACGCCTCAAAAAGGGATTACAAAGACGACGACGACAAAAGGAAGAGCTACTATCCAAGAATTATCATCTTGAGAACGAGGTGGCGCGTCTCAAGAAGCGACTACAAGGACGACGACGACAAAGAGAGGAGTTGCTTAGCAAAAATTATCATTTGGAGAACGAAGTCGCACGACTCAAGAAAACTAGTGGCGGTCATATGGGCGTGCGCAACTGCCTCTACGGCAATAATATGTCAGGACAACGCGATATCCCCCCTGAAATCGGGGAACAGCCCGAGCAACCACCTTTGGAGGCCCCAGGGGCAGCTGCCCCCGGTGCTGGGCCTAGCCCAGCCGAAGAGATGGAGACCGAACCGCCTCACAACGAGCCCATCCCCGTCGAGAATGATGGCGAGGCCTGTGGACCCCCAGAGGTCTCCAGACCCAACTTTCAGGTCCTCAACCCGGCATTCAGGGAAGCTGGAGCCCATGGAAGCTACAGCCCACCTCCTGAGGAAGCAATGCCCTTCGAGGCTGAACAGCCCAGCTTGGGAGGCTTCTGGCCTACACTGGAGCAGCCTGGATTCCCCAGTGGGGTCCATGCAGGCCTTGAGGCCTTCGGCCCAGCACTCATGGAGCCCGGAGCCTTCAGTGGTGCCAGACCAGGCCTGGGAGGATACAGCCCTCCACCAGAAGAAGCTATGCCCTTTGAGTTTGACCAGCCTGCCCAGAGAGGCTGCAGTCAACTTCTCTTACAGGTCCCAGACCTTGCTCCAGGAGGCCCAGGTGCTGCAGGGGTCCCCGGAGCTCCTCCCGAGGAGCCCCAAGCCCTCAGGCCTGCAAAGGCTGGCTCCAGAGGAGGCTACAGCCCTCCCCCTGAGGAGACTATGCCATTTGAGCTTGATGGAGAAGGATTTGGGGACGACAGCCCACCCCCGGGGCTTTCCCGAGTTATCGCACAAGTCGACGGCAGCAGCCAGTTCGCGGCAGTCGCGGCCTCGAGTGCGGTCCGCCTCACTCCCGCCGCGAACGCGCCTCCCCTCTGGGTCCCAGGCGCCATCGGCAGCCCATCCCAAGAGGCTGTCAGACCTCCTTCTAACTTCACGGGCAGCAGCCCCTGGATGGAGATCTCCGGACCCCCGTTCGAGATTGGCAGCGCCCCCGCTGGGGTCGACGACACTCCCGTCAACATGGACAGCCCCCCAATCGCGCTTGACGGCCCGCCCATCAAGGTCTCCGGAGCCCCAGATAAGAGAGAGCGAGCAGAGAGACCCCCAGTTGAGGAGGAAGCAGCAGAGATGGAAGGAGCCGCTGATGCCGCGGAGGGAGGAAAAGTACCCTCTCCGGGGTACGGATCCCCTGCCGCCGGGGCAGCCTCAGCGGATACCGCTGCCAGGGCAGCCCCTGCAGCCCCAGCCGATCCTGACTCCGGGGCAACCCCAGAAGATCCCGACTCCGGGACAGCACCAGCCGATCCTGACTCCGGGGCATTCGCAGCCGATCCCGACTCCGGGGCAGCCCCTGCCGCCCCAGCCGATCCCGACTCCGGGGCGGCCCCTGACGCCCCAGCCGATCCCGACTCCGGGGCGGCCCCTGACGCCCCAGCCGATCCAGATGCCGGGGCGGCCCCTGAGGCTCCCGCCGCCCCTGCGGCTGCTGAGACCCGGGCAGCCCATGTCGCCCCAGCTGCGCCAGACGCAGGGGCTCCCACTGCCCCAGCCGCTTCTGCCACCCGGGCAGCCCAAGTCCGCCGGGCGGCCTCTGCAGCCCCTGCCTCCGGGGCCAGACGCAAGATCCATCTCAGACCCCCCAGCCCCGAGATCCAGGCTGCCGATCCGCCTACTCCGCGGCCTACTCGCGCGTCTGCCTGGCGGGGCAAGTCCGAGAGCAGCCGCGGCCGCCGCGTGTACTACGATGAAGGGGTGGCCAGCAGCGACGATGACTCCAGCGGAGACGAGTCCGACGATGGGACCTCCGGATGCCTCCGCTGGTTTCAGCATCGGCGAAATCGCCGCCGCCGAAAGCCCCAGCGCAACTTACTCCGCAACTTTCTCGTGCAAGCCTTCGGGGGCTGCTTCGGTCGATCTGAGAGTCCCCAGCCCAAAGCCTCGCGCTCTCTCAAGGTCAAGAAGGTACCCCTGGCGGAGAAGCGCAGACAGATGCGCAAAGAAGCCCTGGAGAAGCGGGCCCAGAAGCGCGCAGAGAAGAAACGCAGTAAGCTCATCGACAAACAACTCCAGGACGAAAAGATGGGCTACATGTGTACGCACCGCCTGCTGCTTCTAG'''
aa_seq2 = rsnp.seqmanip.nt2aa(orf2_nt)


#full_construct = ken_sequence_frame_0 + ken_sequence_frame_1
kelong = rsnp.propf.get_k( orf1_nt, .03, 3, 0)[1:]
kelong[1083] = 0  # frame one stop codon
ki = .0244
kon = 9.6e-5
koff = 1.3e-4
kpause_fss_off = .0234
kelong[370] = 1/((1/kelong[370]) + (1/kpause_fss_off))
kpause_fss_on = .0139
length = 1083
kout_frame0 = 3
kout_frame1 = 3
frameshift_location = 370

ha_epitope = 'YPYDVPDYA'
flag_epitope = 'DYKDDDDK'
sun_epitope = 'EELLSKNYHLENEVARLKK'


#poi_0 = rsnp.seqmanip.seq_to_protein_obj(orf1_nt)
poi_1 = rsnp.seqmanip.seq_to_CDS_obj(orf2_nt)

flagtags = [398, 426, 454, 482, 510, 538, 566, 594, 622, 650, 678, 706]
suntags = [406, 434, 462, 490, 518, 546, 574, 602, 630, 658, 686, 714]
hatags = [1, 11, 21, 206, 217, 230, 241, 320, 330, 340]
L = 1428

probe_locations = np.zeros([3,L] )
probe_locations[0,hatags] = 1 # HA tags
#probe_locations[0,flagtags['T_Flag']] = 0 # FLAG TAGS OFF
probe_locations[1,suntags  ] = 2


# Make the mRNA object
poi = rsnp.seqmanip.seq_to_CDS_obj(orf2_nt + 'TGA') # convert a given sequence to a protein of interest object
mRNA = poi['0'][0]                             # pull out the main open reading frame
mRNA_length = 1428             # get the length of the mRNA
mRNA.generate_3frame_tags()                     # call to generate all open reading frames tags

model = rsnp.tasep_model(mRNA, 'FSS_HA') # model object
# Make the kelong mat (manually adding an extra location that is equal to zero, so particles dont run over the simulation)
kelong_mat = np.zeros([3, mRNA_length+1])
kelong_mat[0, :-1] = rsnp.propf.get_k(orf1_nt, ki, 3, 3)[1:-1]
kelong_mat[1, :-2] = rsnp.propf.get_k(orf2_nt, .1, 3, 3)[1:-1]
#kelong_mat[2, :-2] = rsnp.propf.get_k(mRNA.nt_seq[2:-1], .1, 3, 3)[1:-1]
kelong_mat[0, -2] = 0
kelong_mat[1,:370] = 0
kelong_mat[1,370] = kpause_fss_on # PAUSING DUE TO FSS SEQUENCE
kelong_mat[0,370] = kpause_fss_off
model._kelong_mat = kelong_mat #override the current kelongation mat



############ resources ####################


############ states ####################

# we need two states for the mRNA FSS turning on and off:
model.add_states(2, state0=[1,0], names=['off','on'])

############ RXNS ####################


# ribosomal initiation
footprint = 9
# first add the reaction, in this case, we want a lattice reaction at the first
# location for a ribosome to bind (excluded)
init = lambda k,t,p,ke,o,l,pr,s,r,nr: ~np.any(l[0:0+footprint])*k*(t<3000)
model.add_lattice_reaction(init, ki, rxn_name='initiation', exclusion=1, frame=0, loc=0, dexist=1,)

# Now we need a reaction for ribosomes to leave the lattice frame 0 at the end (location 1083)
leave_f0 = lambda k,t,p,ke,o,l,pr,s,r,nr: l[1427]*k #(lattice location 1084 = 1) * parameter
model.add_lattice_reaction(leave_f0, 3, rxn_name='termination_frame0', exclusion=0, frame=0, loc=1427, dexist=-1,)

# Now we need a reaction for ribosomes to leave the lattice frame 1 at the end (location 1083)
leave_f1 = lambda k,t,p,ke,o,l,pr,s,r,nr: l[1427]*k #(lattice location 1084 = 1) * parameter
model.add_lattice_reaction(leave_f1, 3, rxn_name='termination_frame1', exclusion=0, frame=0, loc=1427, dexist=-1,)


############# state RXNS ##############

# mRNA turning on
mRNA_on = lambda k,t,p,ke,o,l,pr,s,r,nr: s[0]*k
model.add_state_reaction(mRNA_on, kon, rxn_name='mRNA on', inds=[0,1],dstates=[-1, 1])

# mRNA turning off
mRNA_off = lambda k,t,p,ke,o,l,pr,s,r,nr: s[1]*k
model.add_state_reaction(mRNA_off, koff, rxn_name='mRNA off', inds=[0,1],dstates=[1, -1])


# DEFAULT STEPPING OF ELONGATION USING THE ELONGATION MATRIX
default_step = lambda k,t,p,ke,o,l,pr,s,r,nr:  [(ke[p[i,2], p[i,3]])*(1 - sum(l[p[i,3]+1:p[i,3]+footprint])) for i in range(nr)]
model.add_ribosome_reaction(default_step, 0, rxn_name='elongation', exclusion=1, dloc=1) #default stepping

# FSS
# JUMP +1 frame if greater than or equal to frameshift location, on frame 0, state = on
FSS = lambda k,t,p,ke,o,l,pr,s,r,nr: [k*(p[i,2] == 0)*(p[i,3] >= frameshift_location)*s[1] for i in range(nr)]
model.add_ribosome_reaction(FSS, 1e5, rxn_name='FSS', exclusion=1, dframe=1, dloc=0)

#initial state
model._state_arr0[0] = 1 # FSS off
# finally specify which reactions are ribosome specific
model._ribosome_reactions = [5,6]
model._constant_reactions = [0,1,2,3,4]

model._lattice_arr0 = np.zeros([model._length+1], dtype=int)


t = np.linspace(0,10000,5001)

if regenerate: 
    #for i in tqdm.tqdm(range(n_model_runs)):
    soln = rsnp.solver.solve_ssa(model, t, n_traj=n_model_runs, burnin=0, verbose=True)
    if resave:
        soln.save(data_save_folder + 'fss_roa',fmt='.npz')
else:
    soln = rsnp.solver.load_soln(data_save_folder + 'fss_roa.npz')
    
plot_kymograph(soln, title='FSS ROA', filename='fss_roa_model_kym', plot_range=2500, profile_t = 1000, n=3)



n = n_model_runs
intensity2 = soln.I
t = np.linspace(0,6000,6001)

av_int_0 = np.mean(intensity2[:500,1200:1400,2])
av_int_1 = np.mean(intensity2[:500,1200:1400,0])
int0 = np.mean(intensity2[:500,1000:3000,2]/av_int_0, axis=0)
int1 = np.mean(intensity2[:500,1000:3000,0]/av_int_1, axis=0)

plt.figure(dpi=global_dpi)

std0 = np.std(intensity2[:500,1000:3000,2]/av_int_0, axis=0)/np.sqrt(n_model_runs)
std1 = np.std(intensity2[:500,1000:3000,0]/av_int_1, axis=0)/np.sqrt(n_model_runs)
plt.plot(soln.t[1000:3000], int0, color=colors[4])
plt.plot(soln.t[1000:3000], int0 + std0, color=colors[4],lw=.5,ls='--')
plt.plot(soln.t[1000:3000], int0 - std0, color=colors[4],lw=.5,ls='--')
plt.plot(soln.t[1000:3000], int1, color=colors[1])
plt.plot(soln.t[1000:3000], int1 + std1, color=colors[1], lw=.5,ls='--')
plt.plot(soln.t[1000:3000], int1 - std1, color=colors[1],lw=.5,ls='--')
plt.plot([3000,3000],[0,1.5],'k--')
plt.xlabel('Time (s)')
plt.ylabel('Normalized Intensity (before run-off)')
if resave:
    plt.savefig('%s/fss_ROA_intensity%s'%(figure_folder,figure_format))




# profile = []
# spottypes = [0,0,0,0]
# for i in tqdm.tqdm(range(n_model_runs)):
#   r1 = np.random.rand()
#   model._state_arr0[0] = 0 # FSS off
#   model._state_arr0[0] = 0 # FSS off
#   if r1 < koff/(kon+koff):
#     model._state_arr0[0] = 1 # FSS off
#   else:
#     model._state_arr0[1] = 1 # FSS off


#   t = np.linspace(0,800,801)
#   soln = rsnp.solver.solve_ssa(model, t, n_traj = 1)
#   c1,_,c2 = soln.I[0,-1,:]
#   if c1 > 5 and c2 > 5:
#     spottypes[3] = spottypes[3] +1
#   if c1 <= 5 and c2 > 5:
#     spottypes[2] = spottypes[2] +1
#   if c1 > 5 and c2 <= 5:
#     spottypes[1] = spottypes[1] +1
#   if c1 <= 5 and c2 <= 5:
#     spottypes[0] = spottypes[0] +1

#     profile[i] = soln.lattice_arr[0,-1]

# plt.figure(dpi=global_dpi)
# plt.bar([0,1,2,3],np.array(spottypes)/np.sum(spottypes),color=['k',colors[1], colors[0], colors[3]])
# plt.gca().set_xticks([0,1,2,3])
# plt.gca().set_xticklabels(['off', '-1F', '0F', '0F / -1F'])
# plt.text(-.5,.85, 'n = %s mRNAs'%n_model_runs)
# plt.text(1.6,.5, r'%s (%.2f)'%(spottypes[2], spottypes[2]/np.sum(spottypes)))
# plt.text(2.65,.05, r'%s (%.2f)'%(spottypes[3], spottypes[3]/np.sum(spottypes)))
# plt.text(0.70,.08, r'%s (%.2f)'%(spottypes[1], spottypes[1]/np.sum(spottypes)))
# plt.text(-.3,.02, r'%s (%.3f)'%(spottypes[0], spottypes[0]/np.sum(spottypes)))
# plt.ylabel('percentage')
# if resave:
#     plt.savefig('%s/fss_ROA_spots%s'%(figure_folder,figure_format))



# def movmean(a, w=3):
#     ret = np.cumsum(a, dtype=float)
#     ret[w:] = ret[w:] - ret[:-w]
#     return ret[w - 1:] / w


# plt.figure(dpi=global_dpi)
# plt.plot(movmean(np.mean(profile, axis=0), 20))
# plt.xlabel('Codon')
# plt.ylabel('Moving Average of Occupation Probability')

# if resave:
#     plt.savefig('%s/fss_ROA_profile%s'%(figure_folder,figure_format))


############################## FRAP
example_mRNA = '''ATGGCGAACCTTGGCTGCTGGATGCTGGTTCTCTTTGTGGCCACATGGAGTGACCTGGGC
                    CTCTGCAAGAAGCGCCCGAAGCCTGGAGGATGGAACACTGGGGGCAGCCGATACCCGGGG
                    CAGGGCAGCCCTGGAGGCAACCGCTACCCACCTCAGGGCGGTGGTGGCTGGGGGCAGCCT
                    CATGGTGGTGGCTGGGGGCAGCCTCATGGTGGTGGCTGGGGGCAGCCCCATGGTGGTGGC
                    TGGGGACAGCCTCATGGTGGTGGCTGGGGTCAAGGAGGTGGCACCCACAGTCAGTGGAAC
                    AAGCCGAGTAAGCCAAAAACCAACATGAAGCACATGGCTGGTGCTGCAGCAGCTGGGGCA
                    GTGGTGGGGGGCCTTGGCGGCTACATGCTGGGAAGTGCCATGAGCAGGCCCATCATACAT
                    TTCGGCAGTGACTATGAGGACCGTTACTATCGTGAAAACATGCACCGTTACCCCAACCAA
                    GTGTACTACAGGCCCATGGATGAGTACAGCAACCAGAACAACTTTGTGCACGACTGCGTC
                    AATATCACAATCAAGCAGCACACGGTCACCACAACCACCAAGGGGGAGAACTTCACCGAG
                    ACCGACGTTAAGATGATGGAGCGCGTGGTTGAGCAGATGTGTATCACCCAGTACGAGAGG
                    GAATCTCAGGCCTATTACCAGAGAGGATCGAGCATGGTCCTCTTCTCCTCTCCACCTGTG
                    ATCCTCCTGATCTCTTTCCTCATCTTCCTGATAGTGGGATGA'''.replace('\n','').replace(' ','')

# Make the mRNA object
poi = rsnp.seqmanip.seq_to_CDS_obj(example_mRNA) # convert a given sequence to a protein of interest object
mRNA = poi['0'][0]                              # pull out the main open reading frame
mRNA_length = len(mRNA.kelong)                  # get the length of the mRNA
mRNA.generate_3frame_tags()                     # call to generate all open reading frames

# manually adding epitopes for two colors
mRNA.multiframe_epitopes[0] = {'T_Flag': [1, 10, 19, 195, 205, 217, 227, 299, 308, 317], 'T_HA':[400,410,420,430]}



#@title model setup
model = rsnp.tasep_model(mRNA,'FRAP') # model object

# Make the kelong mat (manually adding an extra location that is equal to zero, so particles dont run over the simulation)
kelong_mat = np.zeros([3, mRNA_length+1])
kelong_mat[0, :-1] = rsnp.propf.get_k(mRNA.nt_seq, .033, 10, 10)[1:-1]
kelong_mat[1, :-2] = rsnp.propf.get_k(mRNA.nt_seq[1:-2], .1, 10, 10)[1:-1]
kelong_mat[2, :-2] = rsnp.propf.get_k(mRNA.nt_seq[2:-1], .1, 10, 10)[1:-1]
kelong_mat[0, -2] = 0

model._kelong_mat = kelong_mat #override the current kelongation mat

# ribosomal initiation
footprint = 9
parameters=[.03, 10, 500]
# first add the reaction, in this case, we want a lattice reaction at the first
# location for a ribosome to bind (excluded)
init = lambda k,t,p,ke,o,l,pr,s,r,nr: ~np.any(l[0:0+footprint])*k[0]
model.add_lattice_reaction(init, parameters, rxn_name='initiation', exclusion=1, frame=0, loc=0, dexist=1,)

# Now we need a reaction for ribosomes to leave the lattice at the end (location 590)
leave = lambda k,t,p,ke,o,l,pr,s,r,nr: l[590]*k[1] #(lattice location 590 = 1) * parameter
model.add_lattice_reaction(leave, parameters, rxn_name='termination', exclusion=0, frame=0, loc=590, dexist=-1,)

# DEFAULT STEPPING OF ELONGATION USING THE ELONGATION MATRIX
elongation = lambda k,t,p,ke,o,l,pr,s,r,nr: [ (ke[p[i,2], p[i,3]])*(1 - sum(l[p[i,3]+1:p[i,3]+footprint])) for i in range(nr)]
model.add_ribosome_reaction(elongation, parameters, rxn_name='elong', exclusion=1, dloc=1) #default stepping

# FRAP COLOR 1
frap = lambda k,t,p,ke,o,l,pr,s,r,nr: [ ((p[i,4] > 0)*k[2])*(t > 1000)*(t < 1200) for i in range(nr)]
model.add_ribosome_reaction(frap, parameters, rxn_name='frap', exclusion=1, dprobes=[-1], dprobe_inds=[0]) #default stepping

# FRAP COLOR 1
frap2 = lambda k,t,p,ke,o,l,pr,s,r,nr: [ ((p[i,5] > 0)*k[2])*(t > 1000)*(t < 1200) for i in range(nr)]
model.add_ribosome_reaction(frap2, parameters, rxn_name='frap2', exclusion=1, dprobes=[-1], dprobe_inds=[1]) #default stepping


# finally specify which reactions are ribosome specific
model._ribosome_reactions = [2,3,4]
model._constant_reactions = [0,1,]
model._lattice_arr0 = np.zeros([model._length+1], dtype=int)



t = np.linspace(0,2000,2001)


if regenerate: 
    #for i in tqdm.tqdm(range(n_model_runs)):
    soln = rsnp.solver.solve_ssa(model, t, n_traj=n_model_runs, burnin=0, verbose=True)
    if resave:
        soln.save(data_save_folder + 'frap',fmt='.npz')
else:
    soln = rsnp.solver.load_soln(data_save_folder + 'frap.npz')



plot_kymograph(soln, title='FRAP', filename='frap_model_kym')




n = n_model_runs
intensity2 = np.zeros((n,1501,2))
t = np.linspace(0,1500,1501)
  
for i in tqdm.tqdm(range(n)):
  soln =  rsnp.solver.solve_ssa(model, t, n_traj=1)
  intensity2[i] = soln.I[0]


av_int_0 = np.mean(intensity2[:,700:1500,0], axis=0)

plt.figure(dpi=global_dpi)

std0 = np.std(intensity2[:,700:1500,0], axis=0)/np.sqrt(n_model_runs)
plt.plot(np.linspace(700,1499,800), av_int_0, color=colors[0])
plt.plot(np.linspace(700,1499,800), av_int_0 + std0, color=colors[0],lw=.5,ls='--')
plt.plot(np.linspace(700,1499,800), av_int_0 - std0, color=colors[0],lw=.5,ls='--')
plt.fill_between([1000,1200], [0,0], [30,30], alpha=.5, color='gray')
plt.text(1400, 28,'n = %s'%str(n_model_runs))
plt.xlabel('Time (s)')
plt.ylabel('Average Intensity (# probes)')
if resave:
    plt.savefig('%s/frap_avint%s'%(figure_folder,figure_format))


############################ Ribosomal Drafting

example_mRNA = '''ATGGCGAACCTTGGCTGCTGGATGCTGGTTCTCTTTGTGGCCACATGGAGTGACCTGGGC
                    CTCTGCAAGAAGCGCCCGAAGCCTGGAGGATGGAACACTGGGGGCAGCCGATACCCGGGG
                    CAGGGCAGCCCTGGAGGCAACCGCTACCCACCTCAGGGCGGTGGTGGCTGGGGGCAGCCT
                    CATGGTGGTGGCTGGGGGCAGCCTCATGGTGGTGGCTGGGGGCAGCCCCATGGTGGTGGC
                    TGGGGACAGCCTCATGGTGGTGGCTGGGGTCAAGGAGGTGGCACCCACAGTCAGTGGAAC
                    AAGCCGAGTAAGCCAAAAACCAACATGAAGCACATGGCTGGTGCTGCAGCAGCTGGGGCA
                    GTGGTGGGGGGCCTTGGCGGCTACATGCTGGGAAGTGCCATGAGCAGGCCCATCATACAT
                    TTCGGCAGTGACTATGAGGACCGTTACTATCGTGAAAACATGCACCGTTACCCCAACCAA
                    GTGTACTACAGGCCCATGGATGAGTACAGCAACCAGAACAACTTTGTGCACGACTGCGTC
                    AATATCACAATCAAGCAGCACACGGTCACCACAACCACCAAGGGGGAGAACTTCACCGAG
                    ACCGACGTTAAGATGATGGAGCGCGTGGTTGAGCAGATGTGTATCACCCAGTACGAGAGG
                    GAATCTCAGGCCTATTACCAGAGAGGATCGAGCATGGTCCTCTTCTCCTCTCCACCTGTG
                    ATCCTCCTGATCTCTTTCCTCATCTTCCTGATAGTGGGATGA'''.replace('\n','').replace(' ','')

# Make the mRNA object
poi = rsnp.seqmanip.seq_to_CDS_obj(example_mRNA) # convert a given sequence to a protein of interest object
mRNA = poi['0'][0]                              # pull out the main open reading frame
mRNA_length = len(mRNA.kelong)                  # get the length of the mRNA
mRNA.generate_3frame_tags()                     # call to generate all open reading frames

# manually adding epitopes for two colors
mRNA.multiframe_epitopes[0] = {'T_Flag': [1, 10, 19, 195, 205, 217, 227, 299, 308, 317], 'T_HA':[400,410,420,430]}



#@title model setup
model = rsnp.tasep_model(mRNA,'drafting') # model object


# Make the kelong mat (manually adding an extra location that is equal to zero, so particles dont run over the simulation)
kelong_mat = np.zeros([3, mRNA_length+1])
kelong_mat[0, :-1] = rsnp.propf.get_k(mRNA.nt_seq, .033, 10, 10)[1:-1]
kelong_mat[1, :-2] = rsnp.propf.get_k(mRNA.nt_seq[1:-2], .1, 10, 10)[1:-1]
kelong_mat[2, :-2] = rsnp.propf.get_k(mRNA.nt_seq[2:-1], .1, 10, 10)[1:-1]
kelong_mat[0, -2] = 0

model._kelong_mat = kelong_mat #override the current kelongation mat

# ribosomal initiation
footprint = 9
# first add the reaction, in this case, we want a lattice reaction at the first
# location for a ribosome to bind (excluded)
init = lambda k,t,p,ke,o,l,pr,s,r,nr: ~np.any(l[0:0+footprint])*k
model.add_lattice_reaction(init, 0.03, rxn_name='init', exclusion=1, frame=0, loc=0, dexist=1,)


# Now we need a reaction for ribosomes to leave the lattice at the end (location 590)
leave = lambda k,t,p,ke,o,l,pr,s,r,nr: l[590]*k #(lattice location 590 = 1) * parameter
model.add_lattice_reaction(leave, 10, rxn_name='termination', exclusion=0, frame=0, loc=590, dexist=-1,)


# DEFAULT STEPPING OF ELONGATION USING THE ELONGATION MATRIX

#drafting_step = lambda k,t,p,ke,o,l,pr,s,r,nr: [ (ke[p[i,2], p[i,3]] + 40*sum(l[p[i,3]+1:p[i,3]+k[0]]))*(1 - sum(l[p[i,3]+1:p[i,3]+footprint])) for i in range(nr)]
drafting_step = lambda k,t,p,ke,o,l,pr,s,r,nr: [ (ke[p[i,2], p[i,3]] + (sum(l[p[i,3]+1:p[i,3]+k[0]]) > 1) * ((k[0] - min(l[p[i,3]+1:p[i,3]+k[0]] - p[i,3]))/k[0])*k[1])*(1 - sum(l[p[i,3]+1:p[i,3]+footprint])) for i in range(nr)]
# default elong + (boolean ribosome within lookahead) * (lookahead - minimum distance to leading ribosome)/lookahead * speed
#(ke[p[i,2], p[i,3]] + (sum(l[p[i,3]+1:p[i,3]+k[0]])) > 1) * ((k[0] - min(l[p[i,3]+1:p[i,3]+k[0]] - p[i,3]))/k[0])*k[1])

look_ahead = 300
speed = 5
model.add_ribosome_reaction(drafting_step, [look_ahead, speed], rxn_name='drafting', exclusion=1, dloc=1) #default stepping

# finally specify which reactions are ribosome specific
model._ribosome_reactions = [2,]
model._constant_reactions = [0,1,]
model._lattice_arr0 = np.zeros([model._length+1], dtype=int)

model._parameters[0] = .03

t = np.linspace(0,250,251)

if regenerate: 
    #for i in tqdm.tqdm(range(n_model_runs)):
    soln = rsnp.solver.solve_ssa(model, t, n_traj=n_model_runs, burnin=0, verbose=True)
    model._parameters = [0.03, 10, [5, 0]]
    soln2 = rsnp.solver.solve_ssa(model, t, n_traj=n_model_runs, burnin=0, verbose=True)
    if resave:
        soln.save(data_save_folder + 'drafting_on',fmt='.npz')
        soln2.save(data_save_folder + 'drafting_off',fmt='.npz')
else:
    soln = rsnp.solver.load_soln(data_save_folder + 'drafting_on.npz')
    soln2 = rsnp.solver.load_soln(data_save_folder + 'drafting_off.npz')

plot_kymograph(soln, title='drafting', filename='drafting_on_model_kym', n=6)
    
n = n_model_runs
profile_drafting = np.zeros((n,592))
profile_control = np.zeros((n,592))
t = np.linspace(0,6000,6001)
  
for i in tqdm.tqdm(range(n)):
  soln =  rsnp.solver.solve_ssa(model, t, n_traj=1)
  profile_drafting[i] = soln.lattice_arr[0,-1]
  
model._parameters = [0.03, 10, [5, 0]]

for i in tqdm.tqdm(range(n)):
  soln =  rsnp.solver.solve_ssa(model, t, n_traj=1)
  profile_control[i] = soln.lattice_arr[0,-1]


def movmean(a, w=3):
    ret = np.cumsum(a, dtype=float)
    ret[w:] = ret[w:] - ret[:-w]
    return ret[w - 1:] / w


plt.figure(dpi=global_dpi)
plt.plot(movmean(np.mean(profile_control, axis=0), 20))
plt.plot(movmean(np.mean(profile_drafting, axis=0), 20))
plt.xlabel('Codon')
plt.ylabel('Moving Average of Occupation Probability')
plt.legend(['no drafting', 'drafting'])


if resave:
    plt.savefig('%s/drafting_model_profile%s'%(figure_folder,figure_format))
    
    
    
